<a href="https://colab.research.google.com/github/rgalbo/xor_example/blob/master/XOrManyWays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

xor many ways

In [0]:
import numpy as np
# thaw your XOr
n_samples = 10000
n_samples = 10000 // 4 # only 4 unique examples
x = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]] * n_samples)
y = np.array([[1., 0.], [0., 1.], [0., 1.], [1., 0.]] * n_samples)

In [2]:
print(f"x shape: {x.shape}, y shape: {y.shape}")

x shape: (10000, 2), y shape: (10000, 2)


### tensor flow / keras

In [0]:
# TensorFlow and tf.keras
# adapted from the tensorflow 2.0 documentation example
import tensorflow as tf
from tensorflow import keras

In [0]:
model = keras.Sequential([
    keras.layers.Input(shape=(2,)),
    keras.layers.Dense(100, activation=tf.nn.sigmoid),
    keras.layers.Dense(2, activation=tf.nn.sigmoid)
])

In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [6]:
model.fit(x, y, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6942 - accuracy: 0.4906
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6946 - accuracy: 0.5065
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6947 - accuracy: 0.4968
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6937 - accuracy: 0.5098
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6945 - accuracy: 0.5029
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6943 - accuracy: 0.4992
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6929 - accuracy: 0.4972
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6911 - accuracy: 0.5203
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6849 - accuracy: 0.5723
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6715 - accuracy: 0.6533

In [7]:
test_loss, test_acc = model.evaluate(x, y)
print(f'Test accuracy: {test_acc}')

313/313 [==============================] - 0s 992us/step - loss: 0.1120 - accuracy: 1.0000
Test accuracy: 1.0


In [8]:
model.predict(np.array([[1., 0.]]))

array([[0.10114145, 0.9003292 ]], dtype=float32)

In [9]:
model.predict(np.array([[1., 1.]]))

array([[0.8622752 , 0.13627969]], dtype=float32)

### pytorch

In [0]:
# adapted from pytorch documentation example
import torch
import torch.utils.data as utils

# transform to torch tensors
tensor_x = torch.stack([torch.Tensor(i) for i in x]) 
tensor_y = torch.stack([torch.Tensor(i) for i in y])

In [11]:
# N is batch size 
# D_in is input dimension
# H is hidden dimension
# D_out is output dimension
N, D_in, H, D_out = 100, 2, 100, 2

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
    torch.nn.Sigmoid()
)

loss_fn = torch.nn.BCELoss(reduction='mean')

learning_rate = 1e-2
for t in range(5000):
    y_pred = model(tensor_x)
    loss = loss_fn(y_pred, tensor_y)
    if t % 500 == 99:
        print(t, loss.item())

    model.zero_grad()
    loss.backward()

    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

99 0.6584758162498474
599 0.5447440147399902
1099 0.4275079667568207
1599 0.3162926435470581
2099 0.22739599645137787
2599 0.16490991413593292
3099 0.12257596105337143
3599 0.09389626979827881
4099 0.07418420165777206
4599 0.06015053018927574


In [12]:
model(torch.tensor([1.,0.]))

tensor([0.0500, 0.9488], grad_fn=<SigmoidBackward>)

In [13]:
model(torch.tensor([1.,1.]))

tensor([0.9422, 0.0584], grad_fn=<SigmoidBackward>)