<a href="https://colab.research.google.com/github/rgalbo/xor_example/blob/master/XOrManyWays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

xor many ways

In [0]:
import numpy as np
# thaw your XOr
n_samples = 10000
n_samples = 10000 // 4 # only 4 unique examples
x = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]] * n_samples)
y = np.array([[1., 0.], [0., 1.], [0., 1.], [1., 0.]] * n_samples)

In [0]:
print(f"x shape: {x.shape}, y shape: {y.shape}")

x shape: (10000, 2), y shape: (10000, 2)


### tensor flow / keras

In [0]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

In [0]:
model = keras.Sequential([
    keras.layers.Input(shape=(2,)),
    keras.layers.Dense(100, activation=tf.nn.sigmoid),
    keras.layers.Dense(2, activation=tf.nn.sigmoid)
])

In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(x, y, epochs=20)


Train on 10000 samples
Epoch 1/20
10000/10000 [==============================] - 1s 58us/sample - loss: 0.6937 - acc: 0.5116
Epoch 2/20
10000/10000 [==============================] - 1s 56us/sample - loss: 0.6924 - acc: 0.5088
Epoch 3/20
10000/10000 [==============================] - 1s 57us/sample - loss: 0.6863 - acc: 0.5862
Epoch 4/20
10000/10000 [==============================] - 1s 53us/sample - loss: 0.6683 - acc: 0.6564
Epoch 5/20
10000/10000 [==============================] - 1s 55us/sample - loss: 0.6324 - acc: 0.7247
Epoch 6/20
10000/10000 [==============================] - 1s 58us/sample - loss: 0.5771 - acc: 0.8119
Epoch 7/20
10000/10000 [==============================] - 1s 59us/sample - loss: 0.5090 - acc: 0.9119
Epoch 8/20
10000/10000 [==============================] - 1s 59us/sample - loss: 0.4327 - acc: 0.9962
Epoch 9/20
10000/10000 [==============================] - 1s 59us/sample - loss: 0.3574 - acc: 1.0000
Epoch 10/20
10000/10000 [==============================] - 

In [0]:
test_loss, test_acc = model.evaluate(x, y)
print(f'Test accuracy: {test_acc}')

1000/1000 [==============================] - 0s 168us/sample - loss: 0.6934 - acc: 0.5000
Test accuracy: 0.5


In [0]:
model.predict(np.array([[1., 0.]]))

array([[0.02420473, 0.9772031 ]], dtype=float32)

In [0]:
model.predict(np.array([[1., 1.]]))

### pytorch

In [0]:
import torch
import torch.utils.data as utils


tensor_x = torch.stack([torch.Tensor(i) for i in x]) # transform to torch tensors
tensor_y = torch.stack([torch.Tensor(i) for i in y])

In [0]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, 2, 100, 2

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
    torch.nn.Sigmoid()
)

loss_fn = torch.nn.BCELoss(reduction='mean')

learning_rate = 1e-2
for t in range(5000):
    y_pred = model(tensor_x)
    loss = loss_fn(y_pred, tensor_y)
    if t % 500 == 99:
        print(t, loss.item())

    model.zero_grad()
    loss.backward()

    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

99 0.685459554195404
599 0.5556831359863281
1099 0.4157051742076874
1599 0.2944568693637848
2099 0.2067367434501648
2599 0.14891721308231354
3099 0.11087173968553543
3599 0.08542167395353317
4099 0.06796254962682724
4599 0.05560906231403351


In [0]:
model(torch.tensor([1.,0.]))

tensor([0.0453, 0.9557], grad_fn=<SigmoidBackward>)

In [0]:
model(torch.tensor([1.,1.]))

tensor([0.9484, 0.0507], grad_fn=<SigmoidBackward>)